################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean test compile package install

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - secure: IPRPkO5S3/MUEWh1oeTyweSBLwizT1PwNBSDdZv2rFqXQu9xQyCv0PISRexs2AQ3C9NdHr27kTagNsBT69WdDYP/sfMrOEOmeYhHRa9annEciSke8hvNWPhlDluMVb6TGV1jT2zZ1qXVMF2Q1SgGe6b7fSThZbvZlxECbXhXZL0kCL85VpsGBDmyUdEO9FlpwdGaye5Ep/PdEzEVKXsNIkVxXJ66MYjDx9bHYuUQ5z8X3phRawNyLnUiK8yyw8itLMRtBuzocfwPYP50qXXwRijvsj7yZwL7HgsqoNmOJ4226geI6tNv/cAnH7fBqAtZRhBpPwlRy1+o/yCC9SGxSJI3OS+EP5y5trlZstivM4Cw/dEien4RGMhOQSDsmk19ToDdzHqOC8rowtr8T636SukG2mZVOoXdWwBc7l/W0r7/MJPq7JpNXlXDZVUEhLEvP0oG6lXdHf6cBvtDlqXrV7VHaCmE5xSxkzj0KfEITZH4wb4Wk2/bD7if+OWplYsFX3fSBI+erxYWvFksmDpIth7DSj2wkIQW+WOFo7PUWdD1r451cU94k7M0EB2KWVlWdW45SWolvfg/hk7an12Nkgaxg+WuP/JaammBuswso30gi/2Ic7ZI7/6EvrfZlgEle1ARTdOAID3uQlSSPhlZCZfdogcIhhpaCqkMpf0Saj4=
    - secure: HS2Z9Zc7b9vYoMAy2l0t4RSGk03mNKkdF2RK697kGBf00jJ2TrnoWdnRt8OxHEqZDzcDXoO52VJGnXAXo2cFzFcCb5J4VZKL8V8/kXsEMstgUuW0AGeTlK4ebdw9tBg0gM2G/ZB2kk8q1doTgSWKh0ehAMF46Jeq1Fdwjwcn+G/x0nhoc/Ih051k1DFpBBvMkDL0kfR4Ni7Ox/pkozq664+1L/K2HzixmmDpgOpOd6v5UnFJaOkbDQ7zsdzXsAkgmQpuxvr5PuFf15lPF2ANx7KkEFFC8i2zPwqzdbzw8nvK8byZ34H89zNVP2SIj4Y6hXg35uW7KFf2sgEOEl+jpBX9Zy+ub+DreIS+S/VRMr5lcPSLKlFPQlD392SOEfjfe03ARUWweoTMtgzOnOS8lEOiBgOQN2eb/Idt8VVG5joynpmM9+6rSpPEWDYUFZNins/K49Fuw3AVAXuyRpsebyvZEQb1t6m4pYEfmbpaOznYot/h7AJj/1GDkE9hrVcNji96Gq98cwuq1KlMX713EXeA4t79l5bKVGTP2/K3G3XHR5T6JkLd+ctGKUBlUPieskDd55QD5WRfV3w3JUpnZipY6lWGxrNN9BqlcEYYApTo8pbsCrWBsWyREwiZpnfM70zT2JO6Tgun45+AEetFAk7SQ8zJkjDdLpOBTcKUmOM=
